const PICKABLE_ITEM_NAMES = {
    GLOCK_ITEM: 'GLOCK_ITEM',
    PISTOL1_ITEM: 'PISTOL1_ITEM',
    REVOLVER_ITEM: 'REVOLVER_ITEM',
    SMG_SHORT_ITEM: 'SMG_SHORT_ITEM',
    BAYONET_ITEM: 'BAYONET_ITEM',
    PISTOL_AMMO_BOX_ITEM: 'PISTOL_AMMO_BOX_ITEM',
    MAGNUM_AMMO_BOX_ITEM: 'MAGNUM_AMMO_BOX_ITEM',
    SMG_AMMO_BOX_ITEM: 'SMG_AMMO_BOX_ITEM',
    FIRST_AID_KIT_SMALL: 'FIRST_AID_KIT_SMALL',
    FIRST_AID_KIT_MEDIUM: 'FIRST_AID_KIT_MEDIUM',
    FIRST_AID_KIT_LARGE: 'FIRST_AID_KIT_LARGE',
}

const FIELS_NAMES = {
    USER_OPERATION: 'User Operation',
    PDA_OPERARATION: 'PDA Operation',
    ITEM_OPERATION: 'Item Operation',
    JILLS_REPORT: `Jill's Report`,
    INVESTIGATION_NOTES: 'Investigation Notes'
}

const JSON_NAMES = {
    PICKABLE_DESCRIPTIONS: 'PICKABLE_DESCRIPTIONS',
    FILES: 'FILES'
}

// json files
const JSONS = [{
    name: JSON_NAMES.PICKABLE_DESCRIPTIONS,  src: 'assets/docs/pickable_descriptions.json'    
 }, {
    name: JSON_NAMES.FILES, src: 'assets/docs/files.json'
 }];

export { PICKABLE_ITEM_NAMES, FIELS_NAMES, JSON_NAMES, JSONS };